[package]
name = "playground"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""
keywords = []
repository = "https://github.com/qdwang/playground-rs"

[dev-dependencies]

[dependencies]
env_logger = "0.10"
log = "0.4"
pollster = "0.3"
wgpu = "0.16"

[profile.release]
codegen-units = 1
lto="fat"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
