[package]
name = "playground"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = ""
keywords = []
repository = "https://github.com/qdwang/playground-rs"

[dev-dependencies]

[dependencies]
env_logger = "0.10.0"
log = "0.4.19"
pollster = "0.3.0"
wgpu = "0.16.1"
winit = "0.28.6"

[profile.release]
codegen-units = 1
lto="fat"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
